version: '3.8'

services:
  backend:
    image: ghcr.io/suhasdissa/crowdspeech-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:10001:10001"
    volumes:
      - ./data/pb_data:/app/pb_data
    environment:
      - ADMIN_PASSWORD_HASH=${ADMIN_PASSWORD_HASH}
      - PB_PORT=10001
      - PB_DATA_DIR=/app/pb_data
    restart: unless-stopped

  frontend:
    image: ghcr.io/suhasdissa/crowdspeech-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:10000:80"
    restart: unless-stopped
